In [1]:
from tableaudocumentapi import Datasource
import numpy as np
import pandas as pd
import csv, os , datetime
from tableaudocumentapi import Workbook
from tableaudocumentapi import *

In [2]:
os.chdir('document-api-python-master')

In [3]:
os.chdir('samples')

In [4]:
os.chdir('replicate-workbook')

In [6]:
print(os.listdir())

['.ipynb_checkpoints', 'databases.csv', 'replicate_workbook.py', 'sample-superstore.twb', 'World Happiness.twb']

In [8]:
wb = Workbook('sample-superstore.twb')

In [9]:
print(wb.filename)
print(wb.worksheets)
print(wb.datasources)

sample-superstore.twb
['Sheet 1']
[<tableaudocumentapi.datasource.Datasource object at 0x000001D37305ACF8>]

In [10]:
for ds in wb.datasources:
    print(ds.caption)
    print(ds.connections)
    #print(ds.fields)
    print(ds.name)
    print(ds.version)

Orders (sample_superstore)
['<Connection server='superstore.sample.db' dbname='sample_superstore' @ 0x1d3730653c8>']
sqlserver.187oiqw1ls5tey1df9op71phda18
9.3

In [11]:
(wb.datasources[0].fields.values())

dict_values([<tableaudocumentapi.field.Field object at 0x000001D373065438>, <tableaudocumentapi.field.Field object at 0x000001D373065588>, <tableaudocumentapi.field.Field object at 0x000001D373065748>, <tableaudocumentapi.field.Field object at 0x000001D3730656D8>, <tableaudocumentapi.field.Field object at 0x000001D3730657F0>, <tableaudocumentapi.field.Field object at 0x000001D373065898>, <tableaudocumentapi.field.Field object at 0x000001D373065A58>, <tableaudocumentapi.field.Field object at 0x000001D373065A20>, <tableaudocumentapi.field.Field object at 0x000001D373065B00>, <tableaudocumentapi.field.Field object at 0x000001D373065AC8>, <tableaudocumentapi.field.Field object at 0x000001D373065A90>, <tableaudocumentapi.field.Field object at 0x000001D373065B38>, <tableaudocumentapi.field.Field object at 0x000001D373065B70>, <tableaudocumentapi.field.Field object at 0x000001D373065BA8>, <tableaudocumentapi.field.Field object at 0x000001D373065BE0>, <tableaudocumentapi.field.Field object at 0x000001D373065C18>, <tableaudocumentapi.field.Field object at 0x000001D373065C50>, <tableaudocumentapi.field.Field object at 0x000001D373065C88>, <tableaudocumentapi.field.Field object at 0x000001D373065CC0>, <tableaudocumentapi.field.Field object at 0x000001D373065CF8>, <tableaudocumentapi.field.Field object at 0x000001D373065D30>, <tableaudocumentapi.field.Field object at 0x000001D373065D68>, <tableaudocumentapi.field.Field object at 0x000001D373065DA0>, <tableaudocumentapi.field.Field object at 0x000001D373065DD8>, <tableaudocumentapi.field.Field object at 0x000001D373065E10>])

In [12]:
wb.datasources[0].fields.keys()

dict_keys(['[City]', '[Country]', '[Number of Records]', '[Postal Code]', '[Row ID]', '[State]', '[Order ID]', '[Order Date]', '[Ship Date]', '[Ship Mode]', '[Customer ID]', '[Customer Name]', '[Segment]', '[Market]', '[Region]', '[Product ID]', '[Category]', '[Sub-Category]', '[Product Name]', '[Sales]', '[Quantity]', '[Discount]', '[Profit]', '[Shipping Cost]', '[Order Priority]'])

In [13]:
for ds in wb.datasources:
    for f in ds.fields.values():
        print(f.id)
        print(f.caption)
        print(f.role)
        print(f.name)
        print(f.worksheets)
        print(f.calculation)
        print(f.default_aggregation)
        print(f.datatype)
        print(f.description)
        print(f.is_nominal)
        print(f.is_ordinal)
        print(f.is_quantitative)
        print(f.alias)

        print("")

[City]
None
dimension
[City]
[]
None
Count
string
None
True
False
False
None

[Country]
None
dimension
[Country]
[]
None
Count
string
None
True
False
False
None

[Number of Records]
None
measure
[Number of Records]
[]
1
None
integer
None
False
False
True
None

[Postal Code]
None
dimension
[Postal Code]
[]
None
Sum
real
None
False
True
False
None

[Row ID]
None
dimension
[Row ID]
[]
None
Sum
real
None
False
True
False
None

[State]
None
dimension
[State]
[]
None
Count
string
None
True
False
False
None

[Order ID]
None
None
Order ID
[]
None
Count
string
None
False
False
False
Order ID

[Order Date]
None
None
Order Date
[]
None
Year
datetime
None
False
False
False
Order Date

[Ship Date]
None
None
Ship Date
[]
None
Year
datetime
None
False
False
False
Ship Date

[Ship Mode]
None
None
Ship Mode
[]
None
Count
string
None
False
False
False
Ship Mode

[Customer ID]
None
None
Customer ID
[]
None
Count
string
None
False
False
False
Customer ID

[Customer Name]
None
None
Customer Name
[]
None
Count
string
None
False
False
False
Customer Name

[Segment]
None
None
Segment
[]
None
Count
string
None
False
False
False
Segment

[Market]
None
None
Market
['Sheet 1']
None
Count
string
None
False
False
False
Market

[Region]
None
None
Region
[]
None
Count
string
None
False
False
False
Region

[Product ID]
None
None
Product ID
[]
None
Count
string
None
False
False
False
Product ID

[Category]
None
None
Category
[]
None
Count
string
None
False
False
False
Category

[Sub-Category]
None
None
Sub-Category
[]
None
Count
string
None
False
False
False
Sub-Category

[Product Name]
None
None
Product Name
[]
None
Count
string
None
False
False
False
Product Name

[Sales]
None
None
Sales
['Sheet 1']
None
Sum
real
None
False
False
False
Sales

[Quantity]
None
None
Quantity
[]
None
Sum
real
None
False
False
False
Quantity

[Discount]
None
None
Discount
[]
None
Sum
real
None
False
False
False
Discount

[Profit]
None
None
Profit
[]
None
Sum
real
None
False
False
False
Profit

[Shipping Cost]
None
None
Shipping Cost
[]
None
Sum
real
None
False
False
False
Shipping Cost

[Order Priority]
None
None
Order Priority
[]
None
Count
string
None
False
False
False
Order Priority

In [14]:
for ds in wb.datasources:
     for f in ds.fields.values():
            print(f.__dict__.values())

dict_values(['[City]', None, 'string', 'dimension', 'nominal', None, None, None, 'Count', set()])
dict_values(['[Country]', None, 'string', 'dimension', 'nominal', None, None, None, 'Count', set()])
dict_values(['[Number of Records]', None, 'integer', 'measure', 'quantitative', None, '1', None, None, set()])
dict_values(['[Postal Code]', None, 'real', 'dimension', 'ordinal', None, None, None, 'Sum', set()])
dict_values(['[Row ID]', None, 'real', 'dimension', 'ordinal', None, None, None, 'Sum', set()])
dict_values(['[State]', None, 'string', 'dimension', 'nominal', None, None, None, 'Count', set()])
dict_values(['[Order ID]', None, 'string', None, None, 'Order ID', None, None, 'Count', set()])
dict_values(['[Order Date]', None, 'datetime', None, None, 'Order Date', None, None, 'Year', set()])
dict_values(['[Ship Date]', None, 'datetime', None, None, 'Ship Date', None, None, 'Year', set()])
dict_values(['[Ship Mode]', None, 'string', None, None, 'Ship Mode', None, None, 'Count', set()])
dict_values(['[Customer ID]', None, 'string', None, None, 'Customer ID', None, None, 'Count', set()])
dict_values(['[Customer Name]', None, 'string', None, None, 'Customer Name', None, None, 'Count', set()])
dict_values(['[Segment]', None, 'string', None, None, 'Segment', None, None, 'Count', set()])
dict_values(['[Market]', None, 'string', None, None, 'Market', None, None, 'Count', {'Sheet 1'}])
dict_values(['[Region]', None, 'string', None, None, 'Region', None, None, 'Count', set()])
dict_values(['[Product ID]', None, 'string', None, None, 'Product ID', None, None, 'Count', set()])
dict_values(['[Category]', None, 'string', None, None, 'Category', None, None, 'Count', set()])
dict_values(['[Sub-Category]', None, 'string', None, None, 'Sub-Category', None, None, 'Count', set()])
dict_values(['[Product Name]', None, 'string', None, None, 'Product Name', None, None, 'Count', set()])
dict_values(['[Sales]', None, 'real', None, None, 'Sales', None, None, 'Sum', {'Sheet 1'}])
dict_values(['[Quantity]', None, 'real', None, None, 'Quantity', None, None, 'Sum', set()])
dict_values(['[Discount]', None, 'real', None, None, 'Discount', None, None, 'Sum', set()])
dict_values(['[Profit]', None, 'real', None, None, 'Profit', None, None, 'Sum', set()])
dict_values(['[Shipping Cost]', None, 'real', None, None, 'Shipping Cost', None, None, 'Sum', set()])
dict_values(['[Order Priority]', None, 'string', None, None, 'Order Priority', None, None, 'Count', set()])

In [15]:
[f.__dict__.keys() for f in wb.datasources[0].fields.values()][1]

dict_keys(['_id', '_caption', '_datatype', '_role', '_type', '_alias', '_calculation', '_description', '_aggregation', '_worksheets'])

In [16]:
ds1 = pd.DataFrame([f.__dict__.values() for f in wb.datasources[0].fields.values()], columns = [f.__dict__.keys() for f in wb.datasources[0].fields.values()][1])

In [18]:
ds1.head()

,_id,_caption,_datatype,_role,_type,_alias,_calculation,_description,_aggregation,_worksheets
0,[City],None,string,dimension,nominal,None,None,None,Count,{}
1,[Country],None,string,dimension,nominal,None,None,None,Count,{}
2,[Number of Records],None,integer,measure,quantitative,None,1,None,None,{}
3,[Postal Code],None,real,dimension,ordinal,None,None,None,Sum,{}
4,[Row ID],None,real,dimension,ordinal,None,None,None,Sum,{}

## Data Frame Manupilation:
    1. Clean Column names
    2. Add in 
        print(f.name)
    3. Remove []
    4. Add in datasource name 
    5. Add in file

In [19]:
ds2 = pd.DataFrame([f for f in wb.datasources[0].fields.keys()],columns = ['name'])
ds = ds2.join(ds1)
ds.columns

Index(['name', '_id', '_caption', '_datatype', '_role', '_type', '_alias',
       '_calculation', '_description', '_aggregation', '_worksheets'],
      dtype='object')

In [20]:
#Clean Column Names
ds.columns = [col.replace('_','') for col in ds.columns]
ds.columns

Index(['name', 'id', 'caption', 'datatype', 'role', 'type', 'alias',
       'calculation', 'description', 'aggregation', 'worksheets'],
      dtype='object')

In [21]:
ds['name'] = ds['name'].str.replace('[','').str.replace(']','')
ds['name'].sample(7)

0               City
15        Product ID
24    Order Priority
10       Customer ID
7         Order Date
8          Ship Date
19             Sales
Name: name, dtype: object

In [22]:
# Add in data sources and files
#print(ds.caption)    #print(ds.connections)
#print(ds.name)    #print(ds.version)
ds['datasoure_caption'] = str(wb.datasources[0].caption)
ds['datasoure_connections'] = str(wb.datasources[0].connections)
ds['datasoure_name'] = str(wb.datasources[0].name)
ds['datasoure_version'] = str(wb.datasources[0].version)
ds['from_wb'] = str(wb.filename)
ds.sample(4).transpose()

,2,21,6,22
name,Number of Records,Discount,Order ID,Profit
id,[Number of Records],[Discount],[Order ID],[Profit]
caption,None,None,None,None
datatype,integer,real,string,real
role,measure,None,None,None
type,quantitative,None,None,None
alias,None,Discount,Order ID,Profit
calculation,1,None,None,None
description,None,None,None,None
aggregation,None,Sum,Count,Sum
worksheets,{},{},{},{}
datasoure_caption,Orders (sample_superstore),Orders (sample_superstore),Orders (sample_superstore),Orders (sample_superstore)
datasoure_connections,['<Connection server='superstore.sample.db' db...,['<Connection server='superstore.sample.db' db...,['<Connection server='superstore.sample.db' db...,['<Connection server='superstore.sample.db' db...
datasoure_name,sqlserver.187oiqw1ls5tey1df9op71phda18,sqlserver.187oiqw1ls5tey1df9op71phda18,sqlserver.187oiqw1ls5tey1df9op71phda18,sqlserver.187oiqw1ls5tey1df9op71phda18
datasoure_version,9.3,9.3,9.3,9.3
from_wb,sample-superstore.twb,sample-superstore.twb,sample-superstore.twb,sample-superstore.twb